In [2]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

In [7]:
##Q1

#Yes, there is a difference in both the data types.
#The 'list_' is a list datatype while 'array_list' is a numpy array

print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


In [8]:
##Q2

for i in list_:
    print(type(i))
for j in array_list:
    print(type(j))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [15]:
##Q3

array_list = np.array(object = list_, dtype = int)

for i in list_:
    print(type(i))

for j in array_list:
    print(type(j))
    
#There is a difference in the elements of 'array_list' as previously they were string elements#
#while now, there are integer type elements as specified in it.

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [21]:
##Q4

import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

#shape
print('Shape:',num_array.shape)

#size
print('Size:',num_array.size)

Shape: (2, 3)
Size: 6


In [24]:
##Q5

print(np.zeros([3,3]))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [27]:
##Q6

print(np.identity(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
